#if !canImport(ObjectiveC)
import XCTest

extension GroomingSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GroomingSessionTests = [
        ("testGroomingSessionDelete", testGroomingSessionDelete),
        ("testGroomingSessionsContextGet", testGroomingSessionsContextGet),
        ("testGroomingSessionsGet", testGroomingSessionsGet),
        ("testGroomingSessionsPost", testGroomingSessionsPost),
        ("testGroomingSessionsWithoutNamePost", testGroomingSessionsWithoutNamePost),
        ("testMaximumGroomingSessionsPost", testMaximumGroomingSessionsPost),
    ]
}

extension UserStoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserStoryTests = [
        ("testMaximumUserStoryPost", testMaximumUserStoryPost),
        ("testUserStoriesGet", testUserStoriesGet),
        ("testUserStoryCannotDeleteFromAnotherUserStory", testUserStoryCannotDeleteFromAnotherUserStory),
        ("testUserStoryDelete", testUserStoryDelete),
        ("testUserStoryPost", testUserStoryPost),
        ("testUserStoryPostAnEmptyName", testUserStoryPostAnEmptyName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(GroomingSessionTests.__allTests__GroomingSessionTests),
        testCase(UserStoryTests.__allTests__UserStoryTests),
    ]
}
#endif
