#if !canImport(ObjectiveC)
import XCTest

extension RefinementSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RefinementSessionTests = [
        ("testMaximumRefinementSessionsPost", testMaximumRefinementSessionsPost),
        ("testRefinementSessionDelete", testRefinementSessionDelete),
        ("testRefinementSessionsContextGet", testRefinementSessionsContextGet),
        ("testRefinementSessionsGet", testRefinementSessionsGet),
        ("testRefinementSessionsGetOrderedByDateDesc", testRefinementSessionsGetOrderedByDateDesc),
        ("testRefinementSessionsPost", testRefinementSessionsPost),
        ("testRefinementSessionsWithoutNamePost", testRefinementSessionsWithoutNamePost),
    ]
}

extension UserStoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserStoryTests = [
        ("testMaximumUserStoryPost", testMaximumUserStoryPost),
        ("testUserStoriesGet", testUserStoriesGet),
        ("testUserStoryCannotDeleteFromAnotherUserStory", testUserStoryCannotDeleteFromAnotherUserStory),
        ("testUserStoryDelete", testUserStoryDelete),
        ("testUserStoryPost", testUserStoryPost),
        ("testUserStoryPostAnEmptyName", testUserStoryPostAnEmptyName),
    ]
}

extension UserStoryVoteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserStoryVoteTests = [
        ("testSaveVote", testSaveVote),
        ("testVoteGet", testVoteGet),
        ("testVoteView", testVoteView),
        ("testVoteViewWithoutValidParticipant", testVoteViewWithoutValidParticipant),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {[
    testCase(RefinementSessionTests.__allTests__RefinementSessionTests),
    testCase(UserStoryTests.__allTests__UserStoryTests),
    testCase(UserStoryVoteTests.__allTests__UserStoryVoteTests),
]}
#endif
