#if !canImport(ObjectiveC)
import XCTest

extension RefinementSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RefinementSessionTests = [
        ("testRefinementSessionDelete", testRefinementSessionDelete),
        ("testRefinementSessionsContextGet", testRefinementSessionsContextGet),
        ("testRefinementSessionsGet", testRefinementSessionsGet),
        ("testRefinementSessionsPost", testRefinementSessionsPost),
        ("testRefinementSessionsWithoutNamePost", testRefinementSessionsWithoutNamePost),
        ("testMaximumRefinementSessionsPost", testMaximumRefinementSessionsPost),
    ]
}

extension UserStoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserStoryTests = [
        ("testMaximumUserStoryPost", testMaximumUserStoryPost),
        ("testUserStoriesGet", testUserStoriesGet),
        ("testUserStoryCannotDeleteFromAnotherUserStory", testUserStoryCannotDeleteFromAnotherUserStory),
        ("testUserStoryDelete", testUserStoryDelete),
        ("testUserStoryPost", testUserStoryPost),
        ("testUserStoryPostAnEmptyName", testUserStoryPostAnEmptyName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(RefinementSessionTests.__allTests__RefinementSessionTests),
        testCase(UserStoryTests.__allTests__UserStoryTests),
    ]
}
#endif
