name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Linter
      run: swiftlint

    - name: Run tests
      run: swift test -v
