name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Linter for Sources
      run: swiftlint lint Sources

    - name: Linter for Tests
      run: swiftlint lint Tests

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
